[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "custom-hooks"
version = "0.1.0"
description = "Pre-commit hooks for SonarQube"
dependencies = ["requests"]

[project.scripts]
check-sonar-quality-gate = "hooks.sonar_checks:main"
